/* Runs against the real Android WebView in the signed delivery APK, never desktop Chromium. */
const fs=require('fs'),cp=require('child_process'),assert=require('assert');
const adb='/workspace/little-bob-build/sdk/platform-tools/adb',pkg='com.spideystudios.littlebob',out='/workspace/little-bob-build/runtime';fs.mkdirSync(out,{recursive:true});
const report={authority:'Android 15 emulator, software CPU/GPU; not a physical handset or handset performance benchmark',checks:[],errors:[],fixtures:[]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function shell(args){return cp.execFileSync(adb,args,{encoding:'utf8',timeout:90000,maxBuffer:4*1024*1024}).trim()}
let socket,pending=new Map(),seq=0;
async function connect(){const pid=shell(['shell','pidof',pkg]);shell(['forward','tcp:9222','localabstract:webview_devtools_remote_'+pid]);let pages=[];for(let i=0;i<30;i++){try{pages=await(await fetch('http://127.0.0.1:9222/json/list')).json();if(pages.some(v=>v.url.includes('appassets.')))break}catch{}await sleep(1000)}const page=pages.find(v=>v.url.includes('appassets.'));assert(page,'Android WebView page missing');socket=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject});socket.onmessage=e=>{const v=JSON.parse(e.data);if(v.id){const p=pending.get(v.id);if(p){pending.delete(v.id);v.error?p.reject(Error(JSON.stringify(v.error))):p.resolve(v.result)}}else if(v.method==='Runtime.exceptionThrown'){report.errors.push(v.params.exceptionDetails.text+': '+(v.params.exceptionDetails.exception?.description||''))}};await send('Runtime.enable');await send('Page.enable');}
function send(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(Error('CDP timeout: '+method))}},90000).unref()})}
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
async function wait(expression,timeout=120000){const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression))return;await sleep(400)}throw Error('Runtime condition timed out: '+expression)}
async function touch(type,p){await send('Input.dispatchTouchEvent',{type,touchPoints:['touchEnd','touchCancel'].includes(type)?[]:[{id:1,x:p.x,y:p.y}]});}
async function tap(p){await touch('touchStart',p);await sleep(70);await touch('touchEnd',p)}
async function drag(a,b,n=8){await touch('touchStart',a);for(let i=1;i<=n;i++){await touch('touchMove',{x:a.x+(b.x-a.x)*i/n,y:a.y+(b.y-a.y)*i/n});await sleep(30)}await touch('touchEnd',b)}
async function capture(name){const r=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(out+'/'+name+'.png',Buffer.from(r.data,'base64'))}
function pass(name,detail){report.checks.push({name,detail});fs.writeFileSync(out+'/runtime-evidence.json',JSON.stringify(report,null,2));console.log('PASS '+name)}
(async()=>{
  console.log('Starting QA inside the signed Android APK');
  shell(['shell','am','force-stop',pkg]);console.log(shell(['shell','am','start','-W','-n',pkg+'/.MainActivity','--ez','qa_probe','true']));await connect();await wait("!!document.querySelector('#arrival.ready') && !!window.__byteProbe");
  const start=await evaluate("({url:location.href,secure:isSecureContext,title:document.title,viewport:{w:innerWidth,h:innerHeight,dpr:devicePixelRatio},assets:ByteWorldArt.ready,bridge:!!LittleBobNative,media:!!navigator.mediaDevices?.getUserMedia,motion:LittleBobNative.motionAvailable(),battery:!!navigator.getBattery,images:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)})");assert.equal(start.title,'Little Bob');assert(start.secure&&start.bridge&&start.media&&start.motion&&start.battery);assert(!start.images.length);pass('Cold launch loads packaged XIII world on a secure local origin',start);await capture('home');
  // A known awake physical state avoids autonomous targets racing this focused touch test.
  report.fixtures.push('Indoor actor parked awake; competing autonomy suppressed. Gameplay update and rendering remain native RAF.');
  await evaluate("(()=>{const q=__byteProbe;q.home.cancel();q.stopEarthGravity();q.autonomy.choice='qa';q.life.welcomed=true;q.byte.mode='idle';q.byte.x=q.world.w*.45;q.byte.y=q.floorY();})()");
  const body=await evaluate("({x:__byteProbe.byte.x,y:__byteProbe.byte.y-__byteProbe.bodyH()*.2})");await touch('touchStart',body);assert(await evaluate('__byteProbe.byte.grabbed'));await touch('touchMove',{x:body.x+45,y:body.y-110});assert(await evaluate('__byteProbe.byte.grabbed && __byteProbe.byte.y < __byteProbe.floorY()-45'));await touch('touchEnd',body);assert(!await evaluate('__byteProbe.byte.grabbed'));pass('Trusted WebView touch grabs, carries and releases the physical creature');
  await evaluate("document.querySelector('#crystal-wallet').click()");await wait("document.querySelector('#crystal-shop').open");shell(['shell','input','keyevent','4']);await wait("!document.querySelector('#crystal-shop').open");pass('Android Back closes the real shop before leaving the app');
  // Real native SensorManager event injection through Android emulator hardware control.
  await evaluate("__byteProbe.enableEarthGravity()");shell(['emu','sensor','set','acceleration','0:9.81:0']);await wait('__byteProbe.earth.initialized && __byteProbe.earth.y > 1200');const down=await evaluate('({x:__byteProbe.earth.x,y:__byteProbe.earth.y,lastSample:__byteProbe.earth.lastSample})');shell(['emu','sensor','set','acceleration','9.81:0:0']);await wait('__byteProbe.earth.x < -1200');const side=await evaluate('({x:__byteProbe.earth.x,y:__byteProbe.earth.y})');await evaluate('__byteProbe.stopEarthGravity()');shell(['emu','sensor','set','acceleration','0:9.81:0']);pass('Actual Android sensor callback drives existing continuous Earth gravity',{down,side,source:'Emulated accelerometer, not hand-rotated physical phone'});
  // Enter the existing kitchen → outdoor route using the actual rear passage touch.
  report.fixtures.push('Kitchen starting room for the rear-door route; later camera/actor setup for isolated outdoor verbs.');
  await evaluate("(()=>{const q=__byteProbe;q.home.room=5;q.home.cameraX=q.home.space(5).x;q.home.cameraY=0;q.byte.x=q.world.w*.75;q.byte.y=q.floorY();q.byte.mode='idle';q.byte.vx=q.byte.vy=0;})()");const door=await evaluate('__byteProbe.backyard.door()');await tap(door);await wait('__byteProbe.backyard.active');await evaluate('__byteProbe.screenWeb.nextAt=1e9;__byteProbe.backyard.nextInterest=1e9');await capture('backyard');pass('Actual rear passage reaches the dimensional backyard');
  const before=await evaluate('({actor:{x:__byteProbe.backyard.actor.x,y:__byteProbe.backyard.actor.y},camera:{...__byteProbe.backyard.camera}})');const size=await evaluate('({w:innerWidth,h:innerHeight})');await drag({x:size.w*.85,y:size.h*.87},{x:size.w*.85,y:size.h*.47});const after=await evaluate('({actor:{x:__byteProbe.backyard.actor.x,y:__byteProbe.backyard.actor.y},camera:{...__byteProbe.backyard.camera}})');assert(Math.hypot(after.camera.x-before.camera.x,after.camera.y-before.camera.y)>50);assert(Math.hypot(after.actor.x-before.actor.x,after.actor.y-before.actor.y)<25);pass('Touch pans camera independently of the actual outdoor actor',{before,after});
  const call=await evaluate("(()=>{const g=__byteProbe.backyard;g.actor.target=null;const p=g.project(390,440);g.camera.x+=p.x-innerWidth*.5;g.camera.y+=p.y-innerHeight*.65;return g.project(390,440)})()");const actualStart=await evaluate('({x:__byteProbe.backyard.actor.x,y:__byteProbe.backyard.actor.y})');await tap(call);await wait('Math.hypot(__byteProbe.backyard.actor.x-390,__byteProbe.backyard.actor.y-440)<30');pass('Trusted ground tap causes actual-distance outdoor travel',{actualStart,arrival:await evaluate('({x:__byteProbe.backyard.actor.x,y:__byteProbe.backyard.actor.y})')});
  // Preserve exact original save keys across Android process death / offline cold restart.
  await evaluate("(()=>{const q=__byteProbe;q.backyard.actor.target=null;q.home.save();q.backyard.save();window.deliverySave={home:localStorage.getItem('byte-sunburn-home-v1'),garden:localStorage.getItem('byte-backyard-xii-v1'),economy:localStorage.getItem('byte-sunburn-crystals-v1')};})()");const saved=await evaluate('deliverySave');assert(saved.home&&saved.garden&&saved.economy);socket.close();shell(['shell','input','keyevent','3']);await sleep(1500);shell(['shell','am','force-stop',pkg]);shell(['shell','cmd','connectivity','airplane-mode','enable']);shell(['shell','am','start','-W','-n',pkg+'/.MainActivity','--ez','qa_probe','true']);await connect();await wait("!!document.querySelector('#arrival.ready') && !!window.__byteProbe");const restored=await evaluate("({home:JSON.parse(localStorage.getItem('byte-sunburn-home-v1')),garden:JSON.parse(localStorage.getItem('byte-backyard-xii-v1')),economy:JSON.parse(localStorage.getItem('byte-sunburn-crystals-v1')),active:__byteProbe.backyard.active})");const oldGarden=JSON.parse(saved.garden);assert(restored.active);assert(Math.hypot(restored.garden.actor.x-oldGarden.actor.x,restored.garden.actor.y-oldGarden.actor.y)<30);assert.deepEqual(restored.economy,JSON.parse(saved.economy));pass('Offline process restart retains backyard state and persistent wallet/ownership',{restored});await capture('offline-restart');
  assert.equal(report.errors.length,0,report.errors.join('\n'));pass('No unhandled WebView JavaScript exceptions during tested route');socket.close();console.log('ANDROID RUNTIME CHECKS COMPLETE');
})().catch(error=>{report.failure=error.stack;fs.writeFileSync(out+'/runtime-evidence.json',JSON.stringify(report,null,2));console.error(error.stack);try{socket?.close()}catch{}process.exitCode=1});
