const fs=require('fs'),cp=require('child_process'),assert=require('assert'),acorn=require(process.env.BOB_ACORN||'/workspace/spider-byte-sunburn-xiii-qa/tools/node_modules/acorn');
const baseline='72cab43ca61a6b29fbdbc92118faaff18fdbd5a2',rename=s=>s.replace(/Spider Byte/g,'Little Bob').replace(/\bByte\b/g,'Bob').replace(/\bBYTE\b/g,'BOB');
function normalize(v,old=false){if(Array.isArray(v))return v.map(v=>normalize(v,old));if(v&&typeof v==='object'){const result={};for(const[k,x]of Object.entries(v)){if(['start','end','loc','raw'].includes(k))continue;result[k]=normalize(x,old);}return result}return old&&typeof v==='string'?rename(v):v}
const files=cp.execFileSync('git',['ls-tree','-r','--name-only',baseline],{encoding:'utf8'}).trim().split('\n'),results=[];
for(const f of files.filter(f=>!f.includes('/')&&f.endsWith('.js'))){const old=cp.execFileSync('git',['show',baseline+':'+f],{encoding:'utf8'}),next=fs.readFileSync(f,'utf8').replace("(['localhost', '127.0.0.1'].includes(location.hostname) || window.LittleBobNative?.qaEnabled())","['localhost', '127.0.0.1'].includes(location.hostname)");assert.deepStrictEqual(normalize(acorn.parse(old,{ecmaVersion:'latest'}),true),normalize(acorn.parse(next,{ecmaVersion:'latest'})),f+' controller changed');results.push(f)}
for(const f of files.filter(f=>f.startsWith('assets/'))){assert(cp.execFileSync('git',['show',baseline+':'+f],{maxBuffer:32*1024*1024}).equals(fs.readFileSync(f)),f+' artwork changed')}
assert.equal(fs.readFileSync('style.css','utf8'),cp.execFileSync('git',['show',baseline+':style.css'],{encoding:'utf8'}));
assert(!/Spider Byte|\bByte\b|\bBYTE\b/.test(fs.readFileSync('index.html','utf8')));
console.log(JSON.stringify({pass:true,baseline,method:'All original runtime JS ASTs identical after mandatory player-facing name normalization and the explicit Android-only QA gate; all source artwork and CSS byte-identical. Native/compat code is new and requires separate Android runtime validation.',controllers:results},null,2));
