const {chromium,devices}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=process.env.BYTE_QA_OUTPUT||'/tmp/byte-acting-upgrade';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const c=await b.newContext({...devices['Pixel 7'],viewport:{width:390,height:844}});
 // A real Sunburn V-shaped saved home, including an exhausted pantry. Only storage is seeded.
 await c.addInitScript(()=>{if(!sessionStorage.getItem('upgrade-fixture')){localStorage.setItem('byte-sunburn-home-v1',JSON.stringify({room:5,slept:true,found:true,stoneHome:true,things:[{id:'ball',room:1,nx:.4,ny:.9},{id:'sponge',room:4,nx:.115,ny:.61},{id:'stone',room:0,nx:.46,ny:.91},...[0,1,2].map(i=>({id:'biscuit-'+i,room:5,nx:.28+i*.13,ny:.34,bites:0}))]}));localStorage.setItem('byte-sunburn-kitchen-v1',JSON.stringify({meals:3}));localStorage.setItem('byte-sunburn-care-v1',JSON.stringify({washed:true,mud:[0,0,0,0,0,0],dirtEvents:6}));sessionStorage.setItem('upgrade-fixture','1')}});
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.BYTE_QA_URL||'http://127.0.0.1:4194/')+'?probe');await p.waitForSelector('#arrival.ready');
 const read=()=>p.evaluate(()=>{const q=__byteProbe;return{slept:q.home.slept,found:q.home.found,stoneHome:q.home.stoneHome,washed:q.bathroom.washed,meals:q.kitchen.meals,things:q.home.things.map(v=>({id:v.id,room:v.room,bites:v.bites})),phase:q.kitchen.phase,web:q.web.food?.id}});
 const before=await read();assert(before.slept&&before.found&&before.stoneHome&&before.washed);assert(before.things.filter(v=>/^biscuit-[012]$/.test(v.id)).every(v=>v.bites===0));assert.equal(before.things.find(v=>v.id==='biscuit-vi').bites,4);assert.equal(before.things.find(v=>v.id==='ball').room,1);
 await p.waitForFunction(()=>__byteProbe.kitchen.phase==='scheming',undefined,{timeout:25000});const scheme=await read();await p.waitForFunction(()=>__byteProbe.web.food?.id==='biscuit-vi');const web=await read();await p.waitForFunction(()=>__byteProbe.kitchen.meals===4,undefined,{timeout:20000});const eaten=await read();assert.equal(eaten.things.find(v=>v.id==='broccoli').bites,4);await p.reload();await p.waitForSelector('#arrival.ready');const reload=await read();assert.equal(reload.meals,4);assert.equal(reload.things.filter(v=>v.id==='biscuit-vi').length,1);assert.equal(reload.things.find(v=>v.id==='biscuit-vi').bites,0);assert(reload.slept&&reload.found&&reload.stoneHome&&reload.washed);assert.equal(reload.things.find(v=>v.id==='stone').room,0);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'acting-upgrade.json'),JSON.stringify({before,scheme,web,eaten,reload,errors},null,2));await c.close();console.log('PASS exhausted Sunburn V pantry upgrades without resetting history; one new physical biscuit supports natural theft and stays eaten.');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
