const {chromium,devices}=require('playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=process.env.BYTE_QA_OUTPUT||'/tmp/byte-crystal-qa';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:process.env.BYTE_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox']});const results=[];
for(const viewport of [{width:320,height:568},{width:390,height:844},{width:430,height:932},{width:844,height:390}].filter(v=>!process.env.BYTE_QA_LAYOUT||v.width===Number(process.env.BYTE_QA_LAYOUT))){
 const c=await b.newContext({...devices['iPhone 13'],viewport}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.BYTE_QA_URL||'http://127.0.0.1:4191/')+'?probe');await p.waitForSelector('#arrival.ready');
 await p.evaluate(()=>{const q=__byteProbe;q.paused=true;q.life.welcomed=true;q.autonomy.choice='qa';Math.random=()=>.5;q.home.room=3;q.home.cameraX=q.world.w*2;q.home.cameraY=-q.world.h;q.home.cancel();q.finishObby();q.life.scale=1;Object.assign(q.byte,{x:q.world.w*.64,y:q.floorY(),mode:'idle',vx:0,vy:0,spin:0,angle:0});});
 async function step(t){return p.evaluate(t=>{const q=__byteProbe;let firstBounce=null;const trace=[];for(let i=0;i<t*120;i++){const vy=q.byte.vy;q.home.update(1/120);q.update(1/120,performance.now());q.updateLife(1/120);q.updateAutonomy(1/120);q.updateButtonWeb(1/120);q.updateObby(1/120);q.updateButtonPhysics(1/120);q.containRoomBody();
  if(q.obby.hasLaunched&&i%6===0)trace.push({age:q.obby.launchAge,roof:q.crystal.project(q.world.w*.72,-q.world.h*.14).y,edge:q.crystal.project(q.world.w*.16,q.crystal.edgeAt(q.world.w*.16)).y,platforms:q.obby.platforms.filter(p=>!p.launch).length});
  if(vy>0&&q.byte.vy===-930&&!firstBounce){const corners=[[15,15],[q.world.w-15,15],[15,q.world.h-15],[q.world.w-15,q.world.h-15]];firstBounce={age:q.obby.launchAge,allSurface:corners.every(([x,y])=>{const a=q.crystal.unproject(x,y);return q.crystal.contains(a.x,a.y)})};}
 }q.draw(performance.now());return{trace,firstBounce,launched:q.obby.hasLaunched};},t);}
 await step(1);const s=await p.evaluate(()=>{const q=__byteProbe,a=q.obby.platforms[0];const r=document.querySelector('#scene').getBoundingClientRect();return{x:q.byte.x,y:q.byte.y,px:a.x+a.w*.5,py:a.y-q.halfH()-22,left:r.left,top:r.top,h:q.world.h}});
 const d=await c.newCDPSession(p);async function touch(type,x,y){await d.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{id:1,x:x+s.left,y:y+s.top,radiusX:5,radiusY:5,force:1}]});}
 await touch('touchStart',s.x,s.y-20);await touch('touchMove',s.px,s.py);await p.waitForTimeout(180);await touch('touchEnd');const run=await step(4);
 if(!run.firstBounce){const state=await p.evaluate(()=>{const q=__byteProbe;return {byte:q.byte,obby:q.obby,pointer:q.life.pointer,web:q.web,home:{room:q.home.room,trip:q.home.journey,travel:q.home.travel}}});fs.writeFileSync(path.join(out,'layout-failure-'+viewport.width+'.json'),JSON.stringify({viewport,s,run,state},null,2));await p.screenshot({path:path.join(out,'layout-failure-'+viewport.width+'.png'),scale:'css'});}assert(run.firstBounce&&run.firstBounce.allSurface,JSON.stringify({viewport,firstBounce:run.firstBounce}));const pure=run.trace.filter(v=>v.roof>s.h&&v.edge<0);assert(pure.length>=8);assert(pure.every(v=>v.platforms===0));assert(pure.at(-1).age-pure[0].age>.4);await p.screenshot({path:path.join(out,'crystal-layout-'+viewport.width+'.png'),scale:'css'});
 // A resize during flight keeps the material/world reference finite and clears interrupted web ownership.
 await p.evaluate(()=>{__byteProbe.obby.web.pending=true;__byteProbe.obby.web.pointerId=1});await p.setViewportSize({width:viewport.height,height:viewport.width});await p.waitForTimeout(100);assert(!await p.evaluate(()=>__byteProbe.obby.web.pending));assert(await p.evaluate(()=>{const q=__byteProbe;return Number.isFinite(q.obby.crystalBase)&&Number.isFinite(q.byte.y)&&q.home.room===3}));assert(!errors.length);
 results.push({viewport,firstBounce:run.firstBounce,pureSkySeconds:pure.at(-1).age-pure[0].age,errors});await c.close();console.log('PASS crystal layout',viewport);
}fs.writeFileSync(path.join(out,'crystal-layout-results.json'),JSON.stringify(results,null,2));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
