const {chromium,devices}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=process.env.BYTE_QA_OUTPUT||'/tmp/byte-crystal-cache';fs.mkdirSync(out,{recursive:true});
(async()=>{
 const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']}),c=await b.newContext({...devices['Pixel 7'],viewport:{width:390,height:844}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.BYTE_QA_URL||'http://127.0.0.1:4191/')+'?probe');await p.waitForSelector('#arrival.ready');
 const result=await p.evaluate(()=>{const q=__byteProbe;q.paused=true;q.life.welcomed=true;q.autonomy.choice='qa';q.home.room=3;q.home.cameraX=2*q.world.w;q.home.cameraY=-q.world.h;q.life.scale=.7;Object.assign(q.obby,{active:true,hasLaunched:true,seeded:true,crystalBase:-3000,cameraY:-4200,phase:'climb'});document.body.classList.add('obby-away');
  const proto=CanvasRenderingContext2D.prototype,pattern=proto.createPattern,gradient=proto.createLinearGradient;let patterns=0,sceneryGradients=0;proto.createPattern=function(...a){patterns++;return pattern.apply(this,a)};proto.createLinearGradient=function(...a){if(this.canvas.id!=='scene')sceneryGradients++;return gradient.apply(this,a)};
  const t=performance.now();q.draw(t);const warm=q.crystal.stats(),g=sceneryGradients;
  for(let i=1;i<=60;i++)q.draw(t+i*16.7);const staticView=q.crystal.stats(),staticGradients=sceneryGradients-g;
  let maxBytes=0,maxDomBands=0,maxCached=0;for(let i=1;i<=1200;i++){q.obby.cameraY=-4200-i*9;q.byte.y=q.obby.cameraY+320;q.draw(t+1002+i*16.7);const s=q.crystal.stats();maxBytes=Math.max(maxBytes,s.bitmapBytes);maxCached=Math.max(maxCached,s.cachedTiles);maxDomBands=Math.max(maxDomBands,document.querySelectorAll('.crystal-band').length)}
  const final=q.crystal.stats();proto.createPattern=pattern;proto.createLinearGradient=gradient;
  return{warm,staticView,staticGradients,patterns,maxBytes,maxCached,maxDomBands,final,camera:q.obby.cameraY};});
 assert.equal(result.patterns,0);assert.equal(result.staticGradients,0);assert.equal(result.staticView.tileBuilds,result.warm.tileBuilds);assert(result.maxCached<=8&&result.maxDomBands<=6);assert(result.maxBytes<12*1024*1024);assert(result.final.skyBuilds<60&&result.final.opticalBuilds<120);assert(result.final.tileBuilds>20);
 await p.setViewportSize({width:844,height:390});await p.waitForTimeout(150);const resized=await p.evaluate(()=>{const q=__byteProbe;q.draw(performance.now());const r=document.querySelector('#scene').getBoundingClientRect(),s=document.querySelector('#crystal-scenery').getBoundingClientRect();return{cache:q.crystal.stats(),sameBounds:r.left===s.left&&r.top===s.top&&r.width===s.width&&r.height===s.height}});assert(resized.sameBounds);assert(resized.cache.bitmapBytes<12*1024*1024);
 await p.evaluate(()=>{__byteProbe.finishObby();__byteProbe.draw(performance.now())});assert.equal(await p.locator('#crystal-scenery').evaluate(e=>getComputedStyle(e).display),'none');assert(!errors.length);
 fs.writeFileSync(path.join(out,'crystal-cache-results.json'),JSON.stringify({result,resized,errors},null,2));console.log('PASS no patterns or warmed per-frame scenery gradients; bounded raster/DOM caches on a 10,800px expedition; reduced refresh rates; resize and return cleanup.',result);await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
